### ISSUE TITLE
提示语法错误

### ISSUE THREAD

**Issue by JCleqiang** [xuezhulian/classunref#6]
```
jinglian@leqiang222deiMac classunref %  python classunrefs.py
Please input app path
For example:/Users/yuencong/Library/Developer/Xcode/DerivedData/***/Build/Products/Dev-iphoneos/***.app
/Users/jinglian/Desktop/doc.app
Traceback (most recent call last):
  File "classunrefs.py", line 131, in <module>
    path = input('Please input app path\nFor example:/Users/yuencong/Library/Developer/Xcode/DerivedData/***/Build/Products/Dev-iphoneos/***.app\n').strip()
  File "<string>", line 1
    /Users/jinglian/Desktop/doc.app
    ^
SyntaxError: invalid syntax
```

**Comment by xuezhulian** [comment]
python3 classunrefs.py

**Comment by JCleqiang** [comment]
感谢
